[package]
name = "aoc2020"
version = "0.1.0"
authors = ["Paolo Simone <paolo.simone@prima.it>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
counter = "0.5.2"
cli-table = "0.3"
